version: '3.8'

services:
  app:
    build: .
    ports:
      - "8086:8080"
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=stripe
      - DB_PORT=5432
    depends_on:
      - postgres
    networks:
      - stripe-network
    volumes:
      - app_data:/app/data

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=stripe
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - stripe-network

networks:
  stripe-network:
    driver: bridge

volumes:
  postgres_data:
  app_data:
