version: '3.8'

services:
  go-app:
    build: .
    ports:
      - "8080"
    environment:
      - DB_HOST=host.docker.internal
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=stripe
      - DB_PORT=6432
    # depends_on:
    #   - go-postgres
    networks:
      - stripe-network
    volumes:
      - app_data:/app/data

  go-nginx:
    build: ./nginx
    ports:
      - "83:80"
    depends_on:
      - go-app
    networks:
      - stripe-network

  # go-postgres:
  #   image: postgres:16-alpine
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=stripe
  #   ports:
  #     - "6432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - stripe-network

networks:
  stripe-network:
    driver: bridge

volumes:
  # postgres_data:
  app_data:
